spring.application.name=MatriculasSpring
spring.datasource.url=jdbc:postgresql://localhost:5432/matriculas_db
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Habilita cores vibrantes (ANSI) no console do IntelliJ / Terminal
spring.output.ansi.enabled=ALWAYS

# Configuração de logs para ver rotas HTTP e bindings de SQL
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Desativa a varredura de ControllerAdviceBean do Springdoc (evita NoSuchMethodError com Spring 7)
springdoc.override-with-generic-response=false