name: Java CI Spring Boot Pipeline


on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout de código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: './MatriculasSpring/pom.xml'

      - name: Permissao no maven wrapper
        run: chmod +X mvnw

      - name: Compilar e ececutar t.u
        run: /mvnw clean test
